# File: .github/workflows/ci.yml

name: Vibe Player CI

on:
  push:
    branches: [ "**" ] # Run on pushes to all branches
  pull_request:
    branches: [ "main", "master" ] # Run on PRs targeting main or master

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # 1. Setup Node.js and configure caching for npm packages
      # This step handles caching for both the root and the /vibe-player-v2 directories
      # by looking at both package-lock.json files.
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # 2. Install dependencies for the V2 app and the root project.
      # The `setup-node` action automatically handles skipping this if the cache was restored.
      - name: Install root and V2 dependencies
        run: |
          npm ci
          cd vibe-player-v2 && npm ci && cd ..

      # 3. Run all tests and builds as before
      - name: Lint V2
        working-directory: ./vibe-player-v2
        run: npm run lint

      - name: Run V2 unit and component tests
        working-directory: ./vibe-player-v2
        run: npm run test:unit

      - name: Build Vibe Player V2
        working-directory: ./vibe-player-v2
        run: npm run build

      # 4. Correctly cache Playwright browsers
      - name: Cache Playwright browsers
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      # 5. Install Playwright browsers only if the cache was not restored
      - name: Install Playwright and OS dependencies
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Run Playwright E2E tests
        working-directory: ./vibe-player-v2
        run: npx playwright test

      # 6. Cleanup and Reporting
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
