# .github/workflows/ci.yml

name: Vibe Player CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'vibe-player-v2/package-lock.json'

      - name: Install V2 dependencies
        working-directory: ./vibe-player-v2
        run: npm ci

      - name: Lint V2
        working-directory: ./vibe-player-v2
        run: npm run lint

      - name: Run V2 unit and component tests
        working-directory: ./vibe-player-v2
        run: npm run test:unit

      - name: Build Vibe Player V2
        working-directory: ./vibe-player-v2
        run: npm run build

      - name: Restore Playwright cache
        id: cache-playwright-restore # <-- Important ID
        uses: actions/cache/restore@v4
        with:
          path: /home/runner/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('vibe-player-v2/package-lock.json') }}

      - name: Install Playwright and OS dependencies
        if: steps.cache-playwright-restore.outputs.cache-hit != 'true'
        working-directory: ./vibe-player-v2
        run: npx playwright install --with-deps

      - name: Save Playwright cache
        if: always() && steps.cache-playwright-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          # Use the exact key from the restore step to ensure consistency.
          key: ${{ steps.cache-playwright-restore.outputs.cache-primary-key }}
          path: /home/runner/.cache/ms-playwright

      - name: Run Playwright E2E tests
        working-directory: ./vibe-player-v2
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
