# .github/workflows/release.yml
name: Create Release Zip (Official Actions Only)

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  # Need write access to repository contents to create releases and upload assets
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest # Using Ubuntu for easy access to 'zip' command
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Official: Checks out the repository code at the specific tag

      - name: Get the version tag
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        # Standard shell command + GitHub Actions environment variable feature

      - name: Build the zip archive
        run: |
          zip -r vibe-player-${{ env.TAG_NAME }}.zip ./vibe-player-v2/build -x "./vibe-player-v2/build/.DS_Store"
        # Standard shell commands

      - name: Create GitHub Release
        id: create_release # Give this step an ID to reference its outputs
        uses: actions/create-release@v1 # Official: Creates the release entry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for authentication
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: | # Optional: Add release notes here, can be simple or more complex
            Automated release for version ${{ env.TAG_NAME }}.
            Contains the static build of the Vibe Player V2 application.
          draft: false
          prerelease: false # Set to true if needed based on tag format

      - name: Upload Release Asset (Zip)
        uses: actions/upload-release-asset@v1 # Official: Uploads a file to the created release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for authentication
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # Get upload URL from the previous step's output
          asset_path: ./vibe-player-${{ env.TAG_NAME }}.zip # Path to the zip file we created
          asset_name: vibe-player-${{ env.TAG_NAME }}.zip # Name for the asset file on GitHub Releases
          asset_content_type: application/zip # MIME type for zip files
